### ISSUE TITLE
Using your configarution,but can not start nginx.I think if you provide more guide document,your project gets more stars.

### ISSUE THREAD

**Issue by 578141611** [dannote/socks-nginx-module#14]
I insert this to nginx.conf,but can not start nginx.
`location / {
  socks_set_header Host $http_host;
  socks_set_header Proxy-Connection '';
  socks_pass_header Server;
  socks_redirect off;
  socks_http_version 1.1;
  socks_tunnel_header X-Connect;
  socks_buffers 16 16k; 
  socks_buffer_size 32k;
  socks_cache proxy;
  socks_cache_valid 30s;
  socks_cache_use_stale error timeout invalid_header updating
                        http_500 http_502 http_503 http_504;
  socks_pass socks5://127.0.0.1:1080;
}`

like this 
`server {
 listen 1080;
 location / {
 socks_set_header Host $http_host;
 socks_set_header Proxy-Connection '';
 socks_pass_header Server;
 socks_redirect off;
 socks_http_version 1.1;
 socks_tunnel_header X-Connect;
 socks_buffers 16 16k; 
 socks_buffer_size 32k;
 socks_cache proxy;
 socks_cache_valid 30s;
 socks_cache_use_stale error timeout invalid_header updating
 http_500 http_502 http_503 http_504;
 socks_pass socks5://127.0.0.1:1080;
 }
}`
can you help me.or can you provide your nginx.conf to me.thank you very much.

**Comment by dannote** [comment]
Not enough details, closing for now
